name: 'Build Linux'
description: 'Build Linux package'
inputs:
  sourceDir:
    required: true
    description: "Root folder of the sources"
  appName:
    description: "App name"
    required: true
  buildType:
    required: true
    description: "Build type"
  output:
    required: true
    description: "Output path and name of the product"
runs:
  using: "composite"
  steps:
    - name: Download AppImageKit
      shell: bash
      run: |
        curl -OL --retry 5 https://github.com/AppImage/AppImageKit/releases/download/13/appimagetool-x86_64.AppImage
        chmod a+x ./appimagetool-x86_64.AppImage
    - name: Download love
      shell: bash
      run: |
        curl -OL --retry 5 https://github.com/love2d/love/releases/download/11.4/love-11.4-x86_64.AppImage
        chmod +x ./love-11.4-x86_64.AppImage
        ./love-11.4-x86_64.AppImage --appimage-extract
    - name: Pack Techmino Galaxy
      shell: bash
      run: |
        cat ./squashfs-root/bin/love ./target.love > ./squashfs-root/bin/app
        chmod +x ./squashfs-root/bin/app
        rm -rf ./squashfs-root/love.desktop ./squashfs-root/love.svg ./squashfs-root/.DirIcon
        mv ${{ inputs.sourceDir }}/.github/build/linux/${{ inputs.buildType }}/template.desktop ./squashfs-root/${{ inputs.appName }}.desktop
        mv ${{ inputs.sourceDir }}/.github/build/linux/${{ inputs.buildType }}/icon.png ./squashfs-root/icon.png
        ln -s ./squashfs-root/icon.png ./squashfs-root/.DirIcon
        ./appimagetool-x86_64.AppImage ./squashfs-root ${{ inputs.output }}
