name: 'build Mac OS'
description: 'build Mac OS package'
inputs:
  sourceDir:
    required: true
    description: "Root folder of the sources"
  appName:
    required: true
    description: "App name"
  buildType:
    required: true
    description: "Build type"
  versionString:
    required: true
    description: "Version string of the product"
  versionCode:
    required: true
    description: "Version code of the product"
  output:
    required: true
    description: 'Output path and name of the product'
runs:
  using: "composite"
  steps:
    - name: Clone love
      shell: bash
      run: |
        git clone --recurse-submodules https://github.com/love2d/love -b 11.4 --depth 1 --shallow-submodules
    - name: Download framework SDK
      uses: ./.github/actions/get-unzip
      with:
        url: https://github.com/love2d/love/releases/download/11.4/love-11.4-apple-libraries.zip
    - name: Move SDK folder
      shell: bash
      run: |
        mv ./love-apple-dependencies/macOS/Frameworks/ ./love/platform/xcode/macosx
    - name: Modify XCode project
      shell: bash
      run: |
        npm i plist xcode

        cat <<EOT >> temp.js
        const fs = require('fs');
        const plist = require('plist');
        const xcode = require('xcode');

        const pbxprojPath = './love/platform/xcode/love.xcodeproj/project.pbxproj';
        const project = xcode.project(pbxprojPath).parseSync();
        project.updateProductName('${{ inputs.appName }}');
        const resourcesGroupKey = project.findPBXGroupKey({name: 'Resources'});
        const targetKey = project.findTargetKey('"love-macosx"')
        project.addResourceFile('./target.love', {target: targetKey}, resourcesGroupKey);
        fs.writeFileSync(pbxprojPath, project.writeSync());

        const plistPath = './love/platform/xcode/macosx/love-macosx.plist';
        const parsed = plist['parse'](fs.readFileSync(plistPath, 'utf8'));
        parsed['CFBundleName'] = '${{ inputs.appName }}';
        fs.writeFileSync(plistPath, plist['build'](parsed));
        EOT
        
        node temp.js
    - name: move love package
      shell: bash
      run: |
        mv ./target.love ./love/platform/xcode/
    - name: Build MacOS archive
      shell: bash
      run: |
        xcodebuild clean archive \
        -project ./love/platform/xcode/love.xcodeproj \
        -scheme love-macosx \
        -configuration Release \
        -archivePath ./${{ inputs.appName }}.xcarchive \
        PRODUCT_BUNDLE_IDENTIFIER='org.f26_studio.${{ inputs.appName }}'
        MARKETING_VERSION='${{ inputs.versionString }}'
    - name: Export archive
      shell: bash
      run: |
        xcodebuild -exportArchive \
        -archivePath ./${{ inputs.appName }}.xcarchive \
        -exportPath ./${{ inputs.appName }} \
        -exportOptionsPlist ./love/platform/xcode/macosx/macos-copy-app.plist
    - name: Zip app
      shell: bash
      run: |
        ls -l ./${{ inputs.appName }}/
        ditto -c -k --sequesterRsrc --keepParent ./${{ inputs.appName }}/love.app ${{ inputs.output }}

    # - name: Fastlane match
    #   uses: maierj/fastlane-action@v2.0.1
    #   with:
    #     lane: 'get_cert'
    #     subdirectory: 'Techmino-macOS'
    #   env:
    #       API_ID: '${{ inputs.APPLE_API_ID }}'
    #       API_ISSUER: '${{ inputs.APPLE_API_ISSUER }}'
    #       API_KEY: '${{ inputs.APPLE_API_KEY }}'
    #       APP_IDENTIFIER: '${{ inputs.APPLE_APP_IDENTIFIER }}'
    #       KEYCHAIN_NAME: '${{ inputs.APPLE_KEYCHAIN_NAME }}'
    #       KEYCHAIN_PWD: '${{ inputs.APPLE_KEYCHAIN_PWD }}'
    #       MATCH_PASSWORD: '${{ inputs.FASTLANE_MATCH_PWD }}'
    #       MATCH_TOKEN: '${{ inputs.FASTLANE_MATCH_TOKEN }}'
    # - name: Modify template
    #   shell: python
    #   run: |
    #     import datetime
    #     from io import open
    #     thisYear = str(datetime.datetime.today().year)
    #     with open('./.github/build/macOS/info.plist.template', 'r', encoding='utf-8') as file:
    #       data = file.read()
    #       data = data\
    #         .replace('@versionName', '${{ inputs.name }}'[1:])\
    #         .replace('@thisYear', thisYear)\
    #         .replace('@bundleId', '${{ inputs.APPLE_APP_IDENTIFIER }}')
    #     with open('./Techmino-macOS/Techmino.app/Contents/info.plist', 'w+', encoding='utf-8') as file:
    #       file.write(data)
    # - name: Pack
    #   shell: bash
    #   run: |
    #     mv Techmino.love Techmino-macOS/Techmino.app/Contents/Resources
    #     mv CCloader.dylib Techmino-macOS/Techmino.app/Contents/Frameworks
    #     mv ${{ inputs.icon }} Techmino-macOS/Techmino.app/Contents/Resources/iconfile.icns

    #     chmod +x Techmino-macOS/Techmino.app/Contents/Frameworks/CCloader.dylib
    #     chmod +x Techmino-macOS/Techmino.app/Contents/MacOS/love
    # - name: Codesign executable
    #   shell: bash
    #   run: |
    #     security unlock-keychain -p ${{ inputs.TEMP_KEYCHAIN_PASSWORD }} \
    #     ~/Library/Keychains/${{ inputs.TEMP_KEYCHAIN_USER }}-db

    #     [[ $(security find-identity) =~ ([0-9A-F]{40}) ]]

    #     codesign --timestamp --force --strict --deep -v \
    #     --options runtime \
    #     -s ${BASH_REMATCH[1]} \
    #     --entitlements Techmino-macOS/love.entitlements \
    #     Techmino-macOS/Techmino.app
    # - name: Fastlane notarize
    #   uses: maierj/fastlane-action@v2.0.1
    #   with:
    #     lane: 'make_safe'
    #     subdirectory: 'Techmino-macOS'
    #   env:
    #     API_ID: '${{ inputs.APPLE_API_ID }}'
    #     API_ISSUER: '${{ inputs.APPLE_API_ISSUER }}'
    #     API_KEY: '${{ inputs.APPLE_API_KEY }}'
    #     APP_IDENTIFIER: '${{ inputs.APPLE_APP_IDENTIFIER }}'
    #     NOTARIZE_OBJECT: 'Techmino.app'
    # - name: Create DMG file
    #   shell: bash
    #   run: |
    #     brew install create-dmg
    #     create-dmg \
    #       --volname "Techmino for MacOS" \
    #       --volicon "./.github/build/macOS/Techminodisk.icns" \
    #       --window-pos 200 120 \
    #       --window-size 800 500 \
    #       --icon-size 100 \
    #       --icon "Techmino.app" 239 203 \
    #       --background ".github/build/macOS/backgroundImage.tiff" \
    #       --hide-extension "Techmino.app" \
    #       --app-drop-link 565 203 \
    #       "Techmino-macOS/Techmino-macOS.dmg" \
    #       "Techmino-macOS/Techmino.app/"
    # - name: Codesign DMG
    #   shell: bash
    #   run: |
    #     security unlock-keychain -p ${{ inputs.TEMP_KEYCHAIN_PASSWORD }} \
    #     ~/Library/Keychains/${{ inputs.TEMP_KEYCHAIN_USER }}-db

    #     [[ $(security find-identity) =~ ([0-9A-F]{40}) ]]

    #     codesign --timestamp --force --strict --deep -v \
    #     --options runtime \
    #     -s ${BASH_REMATCH[1]} \
    #     --entitlements Techmino-macOS/love.entitlements \
    #     Techmino-macOS/Techmino-macOS.dmg
    # - name: Fastlane notarize
    #   uses: maierj/fastlane-action@v2.0.1
    #   with:
    #     lane: 'make_safe'
    #     subdirectory: 'Techmino-macOS'
    #   env:
    #     API_ID: '${{ inputs.APPLE_API_ID }}'
    #     API_ISSUER: '${{ inputs.APPLE_API_ISSUER }}'
    #     API_KEY: '${{ inputs.APPLE_API_KEY }}'
    #     APP_IDENTIFIER: '${{ inputs.APPLE_APP_IDENTIFIER }}'
    #     NOTARIZE_OBJECT: 'Techmino-macOS.dmg'
    # - name: Finalize
    #   shell: bash
    #   run: |
    #     mv Techmino-macOS/Techmino-macOS.dmg Techmino.dmg
    #     spctl -a -t open --context context:primary-signature -vv Techmino.dmg
