name: "Build Windows"
description: "Build Windows package"
inputs:
  sourceDir:
    required: true
    description: "Root folder of the sources"
  appName:
    required: true
    description: "App name"
  buildType:
    required: true
    description: "Build type"
  versionString:
    required: true
    description: "Version string of the product"
  output:
    required: true
    description: "Output path and name of the product"
runs:
  using: "composite"
  steps:
    - name: Download love
      uses: ./.github/actions/get-unzip
      with:
        url: https://github.com/love2d/love/releases/download/11.4/love-11.4-win64.zip
    - name: Move love
      shell: bash
      run: mv ./love-11.4-win64 ./love
    - name: Download ResourceHacker
      uses: ./.github/actions/get-unzip
      with:
        url: http://www.angusj.com/resourcehacker/resource_hacker.zip
    - name: Update Windows template
      shell: python
      run: |
        Version = '${{ inputs.versionString }}'
        FileVersion = (f"{Version.replace('.', ',')},0")
        with open('${{ inputs.sourceDir }}/.github/build/windows/${{ inputs.buildType }}/template.rc', 'r', encoding='utf8') as file:
          data = file.read()
          data = data\
            .replace('@FileVersion', FileVersion)\
            .replace('@Version', Version)
        with open('./target.rc', 'w+', encoding='utf8') as file:
          file.write(data)
    - name: Pack product folder
      shell: pwsh
      run: |
        cp ${{ inputs.sourceDir }}/.github/build/windows/${{ inputs.buildType }}/icon.ico .\icon.ico
        cmd /c copy /b .\love\love.exe + .\target.love .\love\${{ inputs.appName }}.exe
        del .\love\love.exe
        del .\love\lovec.exe
        del .\love\game.ico
        del .\love\love.ico
        del .\love\changes.txt
        del .\love\readme.txt
        .\ResourceHacker.exe -open .\love\${{ inputs.appName }}.exe -save .\love\${{ inputs.appName }}.exe -action delete -mask "ICONGROUP,,"
        .\ResourceHacker.exe -open .\target.rc -save .\${{ inputs.appName }}.res -action compile
        .\ResourceHacker.exe -open .\love\${{ inputs.appName }}.exe -save .\love\${{ inputs.appName }}.exe -action addoverwrite -res ".\icon.ico" -mask "ICONGROUP,1,"
        .\ResourceHacker.exe -open .\love\${{ inputs.appName }}.exe -save .\love\${{ inputs.appName }}.exe -action addoverwrite -res ".\${{ inputs.appName }}.res" -mask "VERSIONINFO,1,"
        7z a -tzip ${{ inputs.output }} ./love/*
