name: 'Build Bare'
description: 'Build bare love file'
inputs:
  sourceDir:
    required: true
    description: 'Root folder of the sources'
  buildList:
    required: true
    description: 'List of folders and files to be built'
runs:
  using: "composite"
  steps:
    - name: Pack love file
      shell: bash
      run: |
        pushd ${{ inputs.sourceDir }}
        7z a -tzip ./target.love ${{ inputs.buildList }}
        popd
        mv ${{ inputs.sourceDir }}/target.love ./target.love
