name: "Build Android"
description: "Build Android package"
inputs:
  sourceDir:
    required: true
    description: "Root folder of the sources"
  appName:
    required: true
    description: "App name"
  buildType:
    required: true
    description: "Build type"
  versionString:
    required: true
    description: "Version string of the product"
  versionCode:
    required: true
    description: "Version code of the product"
  output:
    required: true
    description: 'Output path and name of the product'
  ANDROID_KEYSTORE_ALIAS:
    required: true
    description: "Signing keystore's alias"
  ANDROID_KEYSTORE_BASE64:
    required: true
    description: "Signing keystore's base64 content"
  ANDROID_KEYSTORE_KEYPASSWORD:
    required: true
    description: "Signing keystore's key password"
  ANDROID_KEYSTORE_STOREPASSWORD:
    required: true
    description: "Signing keystore's keystore password"

runs:
  using: "composite"
  steps:
    - name: Process app name
      id: process-app-name
      shell: python3 {0}
      run: |
        import os
        import re
        os.system('echo ::set-output name=bundle-id::org.F26_Studio.' + re.sub(r'[^A-Za-z0-9]+', '_', '${{ inputs.appName }}'))
    - name: Get Java
      uses: actions/setup-java@v2
      with:
        distribution: "adopt"
        java-version: "11"
    - name: Clone love-android
      shell: bash
      run: |
        git clone --recurse-submodules https://github.com/love2d/love-android -b 11.4 --depth 1 --shallow-submodules
    - name: Extract love package
      shell: bash
      run: |
        7z x ./target.love -o./love-android/app/src/embed/assets/
    - name: Copy resources
      shell: bash
      run: |
        cp -r -f ${{ inputs.sourceDir }}/.github/build/android/${{ inputs.buildType }}/res/* ./love-android/app/src/main/res/
    - name: Update android information
      shell: python
      run: |
        with open('./love-android/app/src/main/AndroidManifest.xml', "r+", encoding='utf-8') as file:
          data = file.read()
          data = data\
            .replace('LÖVE for Android', '${{ inputs.appName }}')\
            .replace('@drawable/love', '@mipmap/icon')
          file.seek(0)
          file.truncate()
          file.write(data)
        with open("./love-android/app/build.gradle", "r+", encoding='utf-8') as file:
          data = file.read()
          data = data\
            .replace('org.love2d.android', '${{ steps.process-app-name.outputs.bundle-id }}')\
            .replace('30', '${{ inputs.versionCode }}')\
            .replace('11.4', '${{ inputs.versionString }}')
          insert_pos = data.find('\n', data.find('proguardFiles')) + 1
          data = data[:insert_pos] + '            signingConfig signingConfigs.release\n' + data[insert_pos:]
          insert_pos = data.find('buildTypes') - 4
          data = data[:insert_pos] + "    signingConfigs {\n" \
                                   "        release {\n" \
                                   "            storeFile file('./android.keystore')\n" \
                                   "            keyAlias '${{ inputs.ANDROID_KEYSTORE_ALIAS }}'\n" \
                                   "            keyPassword '${{ inputs.ANDROID_KEYSTORE_KEYPASSWORD }}'\n" \
                                   "            storePassword '${{ inputs.ANDROID_KEYSTORE_STOREPASSWORD }}'\n" \
                                   "        }\n" \
                                   "    }\n" + data[insert_pos:]
          file.seek(0)
          file.truncate()
          file.write(data)
    - name: Cache gradle
      uses: actions/cache@v3
      with:
        path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
        key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: gradle-
    - name: Cache NDK
      uses: actions/cache@v3
      with:
        path: /usr/local/lib/android/sdk/ndk/21.3.6528147
        key: ndk-21.3.6528147
    - name: Cache Builds
      uses: actions/cache@v3
      with:
        path: |
          ./love-android/.gradle
          ./love-android/love/build
          ./love-android/app/build
        key: build-love-11.4
    - name: Build Techmino Galaxy
      shell: bash
      run: |
        echo "${{ inputs.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > ./love-android/app/android.keystore
        cd ./love-android/
        chmod +x ./gradlew
        ./gradlew assembleEmbedRecordRelease
    - name: Rename APK
      shell: bash
      run: mv ./love-android/app/build/outputs/apk/embedRecord/release/app-embed-record-release.apk ${{ inputs.output }}
